baseURL: "//blog.nody.cc/"
# baseURL: "https://nodyhub.github.io/"
languageCode: "en-us"
title: "Nody´s blog"
theme: "paper-mod"
paginate: 5
enableRobotsTXT: true

menu:
  main:
  - identifier: "about"
    name: "About"
    title: "About"
    url: "/about/"
    weight: 1
  - identifier: "tags"
    name: "Tags"
    title: "Tags"
    url: "/tags/"
    weight: 2
  - identifier: "archive"
    name: "Archive"
    title: "Archive"
    url: "/posts/"
    weight: 3


params:
  social:
    - name: GitHub
      icon: github
      url: https://github.com/NodyHub
    - name: Twitter
      icon: twitter
      url: https://twitter.com/NodyTweet/
  author: "Jan Harrie"
  description: "Blog with infosec content from Jan Harrie"
  mode: dark
  images:
    - images/logo.png
  mainSections:
    - posts
